namespace Player{

  class PlayerModel{
    + int id
    + ReactiveProperty<float> Health
    + ReactiveProperty<float> Ether
    + float atk
  }
  PlayerModel -|> Common.IHealth
  PlayerModel -|> Common.IEther

  class PlayerManager{
    + void Init()
  }

  class PlayerHealthManager{

  }

  class PlayerEtherManager{

  }

  class PlayerInput{

  }

  class PlayerLocomotor{

  }
  PlayerLocomotor -down-> PlayerInput

  class PlayerCamraControllr{
    - GameObject camera
  }
  PlayerCamraControllr -> PlayerInput

  class PlayerWeaponManager{
    - Weapon Weapon
    + void SetWeapon()
  }
  PlayerWeaponManager -left> PlayerInput
  PlayerWeaponManager -> PlayerStatusModel
  PlayerWeaponManager -> Weapon.WeaponAttcker
  PlayerWeaponManager -> Weapon.WeaponEffector

  class PlayerRespawner{

  }

  class PlayerUIManager{

  }

}

namespace Weapon{
  class WeaponAttcker{
    + void SetDamage()
  }

  class WeaponEffector{

  }
}

namespace UI{

  class HealthViewModel{

  }
  HealthViewModel -down> Common.IHealth

  class EtherViewModel{

  }
  EtherViewModel -> Common.IEther

  class WeaponViewModel{

  }
  class TimeViewModel{

  }
  GameManager.TimeManager -> TimeViewModel
  class TeamEtherViewModel{

  }
  class KillLogViewModel{

  }
  GameManager.KillNotifier -> KillLogViewModel

  class RespawnPointViewModel{

  }
  RespawnPointViewModel -> Player.PlayerRespawner

  class HealthViewModel{

  }

}

namespace GameManager{

  class ClientPlayersManager{

  }
  ClientPlayersManager --> Player.PlayerManager

  class KillNotifier{
    + void NoticeKill()
  }

  class TimeManager{
    + void GetCurrentTime()
  }

  class TeamEtherModel{
    + void GetEtherTeam(int teamId)
  }

  class JudgeManager{

  }

}

namespace Common{

  interface IHealth{
    + SetDamage()
  }

  interface IEther{
    + AcquireEther()
  }


  class Damage <<struct>>{

  }
}
